### ISSUE TITLE
Same issue didn't work

### ISSUE THREAD

**Issue by Devilzeyez** [matega/hid_mimouse#2] opened 2021-11-20 19:41 UTC
hey man thanks for ur hard work, but unfortunately it didnt work out for me 
i did what u mentioned with errors and still wont work without the usb dongle ?!
 i'm using linux mint with as in the pic: 

![2021-11-20_21-39](https://user-images.githubusercontent.com/72991780/142738983-93018dfb-eecb-4207-b89d-981e2bb99a00.png)
  
plz advice 

Regards

**Comment by matega** [comment] 2021-11-22 20:01
What error message did you get?

**Comment by Devilzeyez** [comment] 2021-11-22 20:08
didnt get any errors, typo in the 1st post didnt ***

**Comment by matega** [comment] 2021-11-22 20:28
Do you have secure booting and kernel lockdown enabled?
What happens in `dmesg` when you connect your mouse?
What happens when you do `modprobe hid_mimouse` as root?

**Comment by Devilzeyez** [comment] 2021-11-22 20:44
i'm not that expert in linux to answer what u asked!! lol
![mimouse](https://user-images.githubusercontent.com/72991780/142932546-6f30a8ae-d55a-424c-a0f9-dc804c4e2fae.png)

**Comment by Devilzeyez** [comment] 2021-11-22 20:45
i got this msg when running modprobe hid_mimouse

modprobe: ERROR: could not insert 'hid_mimouse': Exec format error

**Comment by Devilzeyez** [comment] 2021-11-25 01:47
any update bro?

**Comment by matega** [comment] 2022-02-18 10:21
I don't know, sorry, i don't know much about Arch. You have an error when you try building the module, maybe you'll find a solution here: https://askubuntu.com/questions/232840/my-makefile-results-in-no-rule-to-make-target-arch-x86-tools-relocs-c-needed

**Comment by ReinhardNzomo** [comment] 2022-11-27 18:47
Is there a similar solution for macOS?

**Comment by matega** [comment] 2022-11-27 19:08
> Is there a similar solution for macOS?

I have no idea and I'm not interested in developing it. Your comment is off-topic in this issue and a duplicate of #1 and #6.

**Comment by matega** [comment] 2022-11-27 19:09
Closing as it's almost a year old with no communication from opener.

**Closed as completed by matega** 2022-11-27 19:09 UTC
